"""add user_decks and user_card_progress

Revision ID: 5082f9bee49b
Revises: cf361de503db
Create Date: 2026-03-08 23:34:31.030215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5082f9bee49b'
down_revision: Union[str, None] = 'cf361de503db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_decks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'deck_id')
    )
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('easiness_factor', sa.Float(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('next_review', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'card_id', name='uq_user_card')
    )
    op.create_index(op.f('ix_user_card_progress_card_id'), 'user_card_progress', ['card_id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_id'), 'user_card_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_card_progress_user_id'), 'user_card_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_card_progress_user_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_id'), table_name='user_card_progress')
    op.drop_index(op.f('ix_user_card_progress_card_id'), table_name='user_card_progress')
    op.drop_table('user_card_progress')
    op.drop_table('user_decks')
    # ### end Alembic commands ###
