"""add deck is_public

Revision ID: cf361de503db
Revises: f9edd3eb6692
Create Date: 2026-03-08 23:25:56.108275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf361de503db'
down_revision: Union[str, None] = 'f9edd3eb6692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'is_public')
    # ### end Alembic commands ###
